# Generated by Django 4.2.5 on 2023-10-01 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_administrator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='administrator',
        ),
    ]
